registries:
  addr: "localhost:8500"

provider:
  service:
    name: "sample-hello-service"
    port: 20000
    check:
      checkPort: 12345
      timeout: "5s"
      interval: "5s"
      deregisterAfter: "10s"

